### ISSUE TITLE
Race condition in collect_test.go

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/refinery#345] opened 2021-11-03 18:17 UTC
Based on the failed circleci test below it appears that `expectedEvents` is read on [line 328](https://github.com/honeycombio/refinery/blob/48470afef29ef1a0561155e9bdddfed6358bd8b1/collect/collect_test.go#L328) in a goroutine via the `assert.Eventually()` and it is later written to via the test code on [line 353](https://github.com/honeycombio/refinery/blob/48470afef29ef1a0561155e9bdddfed6358bd8b1/collect/collect_test.go#L353) causing go to identify a possible race condition.

**Versions**

- Go: 1.16
- Refinery: 1.5.2

**Additional context**

https://app.circleci.com/pipelines/github/honeycombio/refinery/912/workflows/41590f6e-951e-4a8d-b851-4466f1737c9c/jobs/2538

**Comment by MikeGoldsmith** [comment] 2021-11-12 14:01
I've tried to reproduce, and am unable to since #342 where the timeouts were adjusted. Closing for now, we can reopen if it reappears.

**Closed by MikeGoldsmith** 2021-11-12 14:01 UTC
Labels: type: bug
