### ISSUE TITLE
Cache capacity reduction too aggressive (10000x)

### ISSUE THREAD

**Issue by leonsp-ai** [honeycombio/refinery#339] opened 2021-10-13 15:23 UTC
**Versions**

- Go:
- Refinery: 1.5.1

**Steps to reproduce**

1. Configure refinery:
   ```
    resources:
      limits:
        cpu: "1"
        memory: 8Gi
        
        # To size the cache, set MaxAlloc to 80% of the system’s RAM in bytes
        # and set CacheCapacity to the MaxAlloc value divided by 1000.
        CacheCapacity = 6871947
        MaxAlloc = 6871947672
   ```
2. Send a lot of traces through
3. Refinery reduces cache capacity by a factor of 10,000x:
   > time="2021-10-12T14:31:40Z" level=error msg="reducing cache size due to memory overage" alloc=6873706776 cache_size.new=6211 cache_size.previous=6871947
4. Also, `collect_cache_entries_count / collect_cache_capacity = 40,000%`

**Additional context**

This is showing up as an issue for us because we immediately start getting `collect_cache_buffer_overrun` on the pod that auto-reduced its cache capacity, but not on any of the other pods.

This is what Refinery [is doing](https://github.com/honeycombio/refinery/blob/63fd239b38c5ea3b1a10b053d5d3e999518d4127/collect/collect.go#L183):

```golang
	// Reduce cache size by a fixed 10%, successive overages will continue to shrink.
	// Base this on the total number of actual traces, which may be fewer than
	// the cache capacity.
	oldCap := existingCache.GetCacheSize()
	oldTraces := existingCache.GetAll()
	newCap := int(float64(len(oldTraces)) * 0.9)

	// Treat any MaxAlloc overage as an error. The configured cache capacity
	// should be reduced to avoid this condition.
	i.Logger.Error().
		WithField("cache_size.previous", oldCap).
		WithField("cache_size.new", newCap).
		WithField("alloc", mem.Alloc).
		Logf("reducing cache size due to memory overage")
```

1. Why is it reducing it to 90% of oldTraces rather than 90% of oldCap when the [performance tuning recommendation](https://docs.honeycomb.io/manage-data-volume/refinery/scale-and-troubleshoot/#sizing-the-cache) is as follows?
   > To size the cache, set MaxAlloc to 80% of the system’s RAM in bytes and set CacheCapacity to the MaxAlloc value divided by 1000.
2. Is `len(oldTraces)` an accurate count? It seems to be a very different number from the `collect_cache_entries_count` metric.

**Comment by bdarfler** [comment] 2021-10-13 19:26
Hi, @leonsp-ai thanks for opening this issue and for the details you put into it.

Let me start by first asking if you are using Prometheus for capturing Refinery metrics?

I ask because`collect_cache_entries_count` is not a metric if you are sending Refinery metrics to Honeycomb. I'm less familiar with Prometheus but based on the [documentation](https://prometheus.io/docs/practices/histograms/) I believe the `_count` suffix for a histogram metric is the tracks the number of observations during the time period rather than the count of entries in the cache. 

I would recommend looking at the p99 or greater quantile to understand the actual size of the cache, however, you will likely run into #115 which may complicate things.

-----

With that said, let's look at what Refinery is doing here. 

The code that you linked to is part of the routine for checking Refinery's memory usage and attempting to keep it below the `MaxAlloc` setting. If the memory use is above the `MaxAlloc` then Refinery takes a look at the number of traces currently in the cache and lowers the cache size to 90% of that number.

----

Now to your two questions.

First, the reason Refinery is reducing the cache size to 90% of the number of traces is because it assumes that the number of traces is what has caused the memory to expand beyond `MaxAlloc` and therefore it updates the cache size to something less than the current number of cached traces.

The performance tuning recommendation you quoted is a very rough rule of thumb to get folks started. It goes on to say:

> Monitor collect_cache_capacity. Refinery will adjust collect_cache_capacity down to fit the MaxAlloc configuration. Once Refinery reaches a steady state, update CacheCapacity to match collect_cache_capacity.

Second, I believe the answer to this one lies in the confusion over the meaning of `collect_cache_entries_count` that was covered at the top.

-----

Let me know if you have any other questions or if there is something else we can help you with. I've also reached out in Pollinators as that might be easier to go back and forth more quickly.

**Comment by bdarfler** [comment] 2021-10-14 16:22
The best way to look at Refinery memory usage is through the metrics it spits out.

Refinery will export a `memory_inuse` metric if you are sending metrics to Honeycomb. This tracks the bytes of allocated heap objects as reported by the golang runtime. Unfortunately, I don't believe Refinery currently exports this metric to Prometheus. If that would be helpful I'd suggest opening a new issue for that.

The bulk of Refinery's memory usage comes from its internal cache and its various receive and send queues.

The `collect_cache_entries_*` metrics track the number of entries in the cache. It is worth noting that the cache entries are traces that may have many spans. It's helpful to track the `trace_span_count_*` metrics to get a sense of the number of spans in the cache.

The `collector_incoming_queue_*` and `collector_peer_queue_*` metrics track the number of enqueued spans waiting to be processed.

The `libhoney_peer_queue_length` and `libhoney_upstream_queue_length` metrics track the number of enqueued spans waiting to be sent.

-----

I don't have hard and fast numbers when it comes to memory usage on fewer larger nodes vs more smaller nodes. However, I suspect that it won't have a huge impact on memory use. All the spans need to be buffered in memory until the trace completes or the timeout occurs. That fundamental reality doesn't change with the number of nodes. 

That said, fewer larger nodes may help in other ways though since a span will have a higher chance of landing directly on the peer that owns the trace the span belongs resulting in less peer-to-peer traffic forwarding spans to the peer that owns the trace the span belongs to.

-----

If your traffic pattern requires more memory than you would like to allocate to Refinery you can consider pre-sampling in the clients generating the telemetry data and then sampling further in Refinery. This is how we manage our sampling strategy internally at Honeycomb.

**Comment by bdarfler** [comment] 2021-10-20 16:27
@leonsp-ai thanks, I look forward to the `MinAlloc` issue. Though, I now realize I didn't think that through well enough. I think what is needed is not `MinAlloc` but a `MinCacheCapacity`. The issue isn't that Refinery is taking up to little memory, it's that you would like a floor on how small the cache can be sized down when Refinery takes up too much memory.

I think your second idea could be an interesting one to include in a `MinCacheCapcity` conversation. Maybe if Refinery is at the MinCacheCapacity and still uses more than `MaxAlloc` then it could gracefully shut down rather than continue going. An interesting twist to add to the new issue.

I'm going to close this for now but feel free to request we re-open it if needed.

**Closed as completed by bdarfler** 2021-10-20 16:27 UTC
Labels: status: info needed
