### ISSUE TITLE
Validate the rules/config while converting a refinery 1.x helm chart values

### ISSUE THREAD

**Issue by fujin** [honeycombio/refinery#958] opened 2023-12-20 01:12 UTC
**Is your feature request related to a problem? Please describe.**
I ran the conversion tool on my helm chart values, which worked and gave me values that look like they would work. when I booted up refinery it crashed, as the rule had an invalid condition:

```
Validation failed for rules file /etc/refinery/rules.yaml:
  Within sampler __default__: Within field RulesBasedSampler.Rules[9]: Within field Rules.Conditions[0]: field Conditions.Operator (equals) must be one of [= != > < >= <= starts-with contains does-not-contain exists not-exists has-root-span]
 ```

I can't run `validate rules` on this helm chart values yaml either.

**Describe the solution you'd like**
During the generation of the 2.x converted rules, validate them

**Describe alternatives you've considered**

**Additional context**

**Comment by JamieDanielson** [comment] 2024-01-03 15:56
Adding an extra note for context, from the [slack thread in pollinators](https://honeycombpollinators.slack.com/archives/C01BZ3J7RMJ/p1703027717921899):

> The old rule was probably silently not working (?)
> ...
> if I output the new rules as an intermediary step or dump out the configmap, `convert validate rules --input v2rules.yaml` fails as expected. but I didn't see this using `convert helm`.

**Comment by fujin** [comment] 2024-01-03 17:27
IndeedOn 4/01/2024, at 04:57, Jamie Danielson ***@***.***> wrote:﻿
Adding an extra note for context, from the slack thread in pollinators:

The old rule was probably silently not working (?)
...
if I output the new rules as an intermediary step or dump out the configmap, convert validate rules --input v2rules.yaml fails as expected. but I didn't see this using convert helm.

**Comment by TylerHelmuth** [comment] 2024-01-16 21:40
@fujin this sounds like https://github.com/honeycombio/helm-charts/issues/286

**Comment by MikeGoldsmith** [comment] 2024-01-29 16:59
Hey @fujin - thanks for raising the issue.

After discussion we're unsure if we could make this experience better. A silently failing rules config, invalid spacing, in the helm chart is not possible for us detect using`convert helm` because we don't get the whole config, just the specified config. The conversion tool does work as intended for valid config's so if it fails migration we would need to review the config to manually fix. If you need help with that, please reach out.

I'm going to close this for now as there's no action for us to take. Please feel free to reopen if you need more help.

**Closed by MikeGoldsmith** 2024-01-29 16:59 UTC
Labels: type: enhancement
